import json
from typing import Dict

DEFAULT_LANGUAGE = "en"
_current_language = DEFAULT_LANGUAGE
_locales: Dict[str, Dict[str, str]] = {}

_language_names = {
    "en": "English",
    "ro": "Română",
    "ru": "Русский",
    "de": "Deutsch",
    "fr": "Français",
}

def load_locales():
    """
    Loads localization strings.
    In a real application, this might load from multiple JSON files in a directory.
    """
    _locales["en"] = {
        "app_title": "PY2PY — Secure file sharing",
        "app_name_short": "PY2PY",
        "py2py_device_name": "PY2PY device",
        "main_title": "Secure local file sharing",
        "main_subtitle": "Choose what you want to do.",
        "send_button": "Send a file",
        "receive_button": "Receive files",
        "trusted_button": "Manage trusted devices",
        "settings_button": "Settings",
        "settings_title": "Application Settings",
        "settings_language_label": "Language",
        "settings_language_restart_hint": "A reload is required to fully apply language changes.",
        "settings_receive_location_label": "File Receive Location",
        "settings_receive_mode_label": "Receive Mode",
        "settings_receive_mode_fixed": "Save to a fixed location",
        "settings_receive_mode_ask": "Ask where to save for each transfer",
        "settings_change_location_button": "Change Location",
        "settings_save_button": "Save Settings",
        "settings_show_only_recommended_interfaces_label": "Show only recommended network interfaces",
        "settings_show_only_recommended_interfaces_subtitle": "When enabled, the network dropdown will hide virtual or special-purpose adapters.",
        "settings_saved_message": "Settings saved. Some changes may require a restart.",

        # UI General
        "status_ready": "Ready",
        "clear_all_button": "Clear All",
        "got_it_button": "Got it",
        "ignore_button": "Ignore",
        "open_folder_button": "Open folder",
        "cancel_button": "Cancel",
        "cancel_transfer_button_short": "Cancel Transfer",
        "ok_continue_button": "OK, Continue",
        "reject_button": "Reject",
        "apply_and_reload_button": "Apply & Reload",
        "apply_button": "Apply",
        "apply_and_reload_tooltip": "Saves language and reloads the UI to apply changes.",
        "accept_button": "Accept",
        "add_button": "Add",
        "revoke_button": "Revoke",

        # Send Page
        "send_files_title": "Send Files",
        "connection_mode_title": "Connection Mode",
        "configure_connection_title": "Configure Connection",
        "select_files_title": "Select Files & Folders",
        "discovery_mode_title": "Discovery Mode",
        "send_mode_auto": "Auto Mode (LAN)",
        "send_mode_manual": "Manual Mode (LAN/WAN)",
        "send_mode_direct_ip": "Direct IP",
        "send_mode_subnet_scan": "Subnet Scan",
        "lan_selector_label": "Network interface",
        "lan_helper_text": "The default is the adapter currently used for internet access.",
        "refresh_network_list_tooltip": "Refresh network list",
        "scan_for_receivers_button": "Scan for receivers",
        "check_status_button": "Check Status",
        "send_to_specific_ip_title": "Send to a specific IP address (LAN or WAN)",
        "receiver_ip_label": "Receiver IP Address",
        "receiver_ip_hint": "e.g., 192.168.1.50 or 2001:db8::1",
        "port_label": "Port",
        "send_to_ip_button": "Send to IP",
        "scan_subnet_title": "Scan a network subnet for receivers",
        "subnet_scan_label": "Subnet to Scan (CIDR)",
        "subnet_scan_hint": "e.g., 192.168.1.0/24",
        "what_is_this_tooltip": "What is this?",
        "scan_subnet_button": "Scan Subnet",
        "stage_data_title": "Stage data for encrypted transfer",
        "add_files_button": "Add Files",
        "add_files_subtitle": "Select loose items",
        "add_folders_button": "Add Folders",
        "add_folders_subtitle": "Select entire directory structures",
        "selected_file_none": "No files or folders selected",
        "selected_file_count": "{count} item(s) staged for transfer:",
        "remove_from_list_tooltip": "Remove from transfer list",
        "devices_ready_title": "Devices ready to receive",
        "devices_ready_subtitle": "Scanning your local network for other PY2PY receivers.",
        "device_list_ip_prefix": "IP: {ip}",
        "device_list_send_button": "Send",

        # Receive Page
        "receive_files_title": "Receive files",
        "listen_on_title": "Listen for incoming files on",
        "restart_receiver_button": "Restart Receiver",
        "stop_receiver_button": "Stop Receiver",
        "network_settings_title": "Network Settings",
        "listening_port_label": "Listening Port",
        "wan_receive_info": "To receive files from the internet (WAN), you must configure your router to forward the chosen TCP port to this device's local IP. Use the 'High Security' or 'Public' firewall mode. This is an advanced feature; proceed with caution.",
        "firewall_access_control_title": "Firewall / Access Control",
        "firewall_access_control_subtitle": "Control which devices can send you files. A receiver restart is required for changes to take effect.",
        "firewall_mode_lan": "LAN Only (Default, Recommended)",
        "firewall_mode_high_security": "High Security (Trusted Devices & Whitelist)",
        "firewall_mode_public": "Allow Everyone (Unsafe for Internet)",
        "high_security_panel_info": "Only allows transfers from devices you have 'trusted' or IPs you manually add to the whitelist below.",
        "lan_only_panel_info": "Allows any device on your local private network (e.g., your home WiFi). Blocks connections from the public internet.",
        "public_panel_info": "WARNING: Allows any device from anywhere, including the public internet, to attempt a file transfer. Only use if you understand the risks.",
        "add_ip_whitelist_label": "Add IP to Whitelist",
        "add_ip_whitelist_hint": "e.g., 192.168.1.100",

        # Trusted Devices Page
        "trusted_devices_title": "Trusted devices",
        "trusted_devices_subtitle": "Devices you have chosen to trust during a transfer. You can revoke trust at any time.",
        "no_trusted_devices": "No trusted devices stored.",
        "unnamed_device": "Unnamed Device",
        "fingerprint_label": "Fingerprint: {fp}",
        "trusted_since_label": "Trusted since: {date}",
        "unknown_date": "Unknown date",

        # Dialogs & Popups
        "transfer_complete_title": "Transfer complete",
        "transfer_complete_message": "{filename} arrived successfully.\nSaved in: {location}",
        "verify_receiver_title": "Verify receiver",
        "verify_receiver_instructions": "Compare this code with the receiver's incoming-transfer dialog. Continue only when both codes are identical.",
        "codes_match_button": "Codes match",
        "cancel_transfer_button": "Cancel transfer",
        "incoming_file_title": "Incoming file",
        "trust_device_checkbox": "Trust this device (remember for future transfers)",
        "incoming_transfer_from": "Incoming transfer from {name} ({fp})",
        "filename_label": "Filename: {filename}",
        "size_label": "Size: {size}",
        "compare_code_prompt": "Compare this code with the sender before accepting:",
        "verification_code_label": "Verification code: {code}",
        "receiver_label": "Receiver: {name}",
        "receiver_identity_label": "Receiver identity: {fp}",
        "win_firewall_title": "Windows Firewall",
        "win_firewall_prompt": "To discover devices and receive files, PY2PY needs to add rules to the Windows Firewall. This requires administrator permission and may trigger a UAC prompt.",
        "linux_firewall_title": "Linux Firewall Configuration",
        "linux_firewall_prompt": "Your firewall may be blocking connections. To allow PY2PY to receive files, you may need to run the following command(s) in a terminal:",
        "subnet_help_title": "Scanning a Subnet",
        "subnet_help_line1": "This feature is for advanced users on complex networks where automatic discovery (mDNS/Zeroconf) may not work across subnets.",
        "subnet_help_line2": "Enter a network range in CIDR notation to perform a fast unicast scan for PY2PY receivers.",
        "subnet_help_examples": "Examples:",
        "subnet_help_example1": "  • 192.168.100.0/24 (scans 192.168.100.1 to .254)",
        "subnet_help_example2": "  • 2001:db8:abcd::/48 (scans a large IPv6 range)",
        "dialog_title_select_save_folder": "Select folder to save received files",
        "dialog_title_select_send_folder": "Select a folder to send",
        "dialog_title_select_default_receive_folder": "Select default receive folder",

        # Status Messages
        "status_checking_peer_status": "Checking status of {ip}:{port}...",
        "status_peer_online": "Peer at {ip}:{port} is online and reachable.",
        "status_peer_offline": "Peer at {ip}:{port} is offline or not responding.",
        "status_checking_short": "Checking...",
        "status_online_short": "Online",
        "status_offline_short": "Offline",
        "status_invalid_short": "Invalid",
        "status_item_removed": "Item removed.",
        "status_skipped_not_exist": "Skipped (does not exist): {path}",
        "status_choose_receiver": "Choose a receiver to start the encrypted transfer.",
        "status_selection_cleared": "Selection cleared.",
        "status_refreshing_interfaces": "Refreshing network interfaces...",
        "status_interfaces_updated": "Network interfaces updated. You may need to restart scanning/receiving.",
        "status_transfer_cancelled": "Transfer cancelled.",
        "status_transfer_cancelled_by_user": "Transfer cancelled by user.",
        "status_announcing_as_receiver": "Announcing device on {ip}:{port} as a Receiver...",
        "status_stopping_announcement": "Stopping announcement...",
        "status_trusted_receiver": "Trusted receiver detected; skipping manual verification.",
        "status_file_selection_cancelled": "File selection cancelled.",
        "status_folder_selection_cancelled": "Folder selection cancelled.",
        "status_transfer_in_progress": "Transfer already in progress, please wait.",
        "status_select_files_first": "Select one or more files or folders first.",
        "status_invalid_port": "Invalid port: {port}. Must be between 1 and 65535.",
        "status_invalid_subnet_format": "Invalid subnet format: {subnet}",
        "status_preparing_transfer": "Preparing encrypted transfer...",
        "status_found_receiver_details": "Found receiver: {name} at {ip}:{port}",
        "status_requesting_firewall_perms": "Requesting firewall permissions... Please accept the UAC prompt.",
        "status_firewall_not_configured": "Firewall not configured. Discovery and receiving may fail.",
        "status_receiver_disconnected": "Receiver disconnected: {name}",
        "status_enter_valid_sender_ip": "Enter a valid IP address for the sender interface.",
        "status_scanning_on_target": "Scanning for receivers on {target}...",
        "status_enter_subnet": "Please enter a subnet to scan.",
        "status_subnet_scan_complete": "Subnet scan complete.",
        "status_scanning_subnet": "Scanning subnet {subnet} on port {port}...",
        "status_enter_valid_listen_ip": "Enter a valid IP address to listen on.",
        "status_receiver_start_failed": "Failed to start receiver server.",
        "status_ready_to_receive_on": "Ready to receive on {ip}:{port}.",
        "status_receiving_stopped": "Receiving stopped.",
        "status_listening_securely_on": "Listening securely on {addrs}",
        "status_incoming_connection": "Incoming connection from {ip}",
        "status_blocked_public_ip": "Connection from public IP {ip} blocked by 'LAN Only' firewall policy.",
        "status_blocked_invalid_ip": "Could not validate IP {ip}. Blocking connection.",
        "status_establishing_secure_connection": "Establishing secure connection…",
        "status_secure_channel_established": "Secure channel established.",
        "status_blocked_high_security": "Connection from {ip} ({fp}) blocked by 'High Security' policy (not trusted or whitelisted).",
        "status_transfer_rejected": "Transfer rejected.",
        "status_receiving_file": "Receiving {filename}…",
        "status_verifying_unpacking": "Transfer received. Verifying and unpacking...",
        "status_client_disconnected_normal": "Client disconnected after transfer, which is normal.",
        "status_received_successfully": "Received {filename} successfully.",
        "status_restarting_receiver": "Restarting receiver...",
        "status_settings_saved_restart": "Settings saved. Restart receiver to apply.",
        "settings_saved_snackbar": "Settings saved!",
        "status_transfer_failed": "Transfer failed: {error}",
        "all_interfaces_target": "all interfaces",

        # Errors
        "error_ip_required": "IP is required",
        "error_invalid_port": "Invalid port",
        "error_subnet_required": "Subnet is required",
        "error_invalid_ip": "Invalid IP address",
        "error_invalid_port_range": "Invalid port (1024-65535)",
        "error_bind_failed": "Failed to listen on {ip}:{port}. The address may not be available or is in use.",

        # Progress Handler
        "role_sending": "Sending",
        "role_receiving": "Receiving",
        "progress_label": "{role}: {completed} of {total} ({percent:.0f}%) - {speed}",
        "progress_label_no_speed": "{role}: {completed} of {total} ({percent:.0f}%)",
    }
    _locales["ro"] = {
        "app_title": "PY2PY — Partajare sigură de fișiere",
        "app_name_short": "PY2PY",
        "py2py_device_name": "Dispozitiv PY2PY",
        "main_title": "Partajare locală sigură de fișiere",
        "main_subtitle": "Alegeți ce doriți să faceți.",
        "send_button": "Trimite un fișier",
        "receive_button": "Primește fișiere",
        "trusted_button": "Gestionează dispozitivele de încredere",
        "settings_button": "Setări",
        "settings_title": "Setările Aplicației",
        "settings_language_label": "Limbă",
        "settings_language_restart_hint": "Este necesară o reîncărcare pentru a aplica complet modificările de limbă.",
        "settings_receive_location_label": "Locație Primire Fișiere",
        "settings_receive_mode_label": "Mod Primire",
        "settings_receive_mode_fixed": "Salvează într-o locație fixă",
        "settings_receive_mode_ask": "Întreabă unde se salvează pentru fiecare transfer",
        "settings_change_location_button": "Schimbă Locația",
        "settings_save_button": "Salvează Setările",
        "settings_show_only_recommended_interfaces_label": "Afișează doar interfețele de rețea recomandate",
        "settings_show_only_recommended_interfaces_subtitle": "Când este activat, meniul de rețea va ascunde adaptoarele virtuale sau cu scop special.",
        "settings_saved_message": "Setările au fost salvate. Unele modificări pot necesita o repornire.",

        # UI General
        "status_ready": "Gata",
        "clear_all_button": "Șterge Tot",
        "got_it_button": "Am înțeles",
        "ignore_button": "Ignoră",
        "open_folder_button": "Deschide folderul",
        "cancel_button": "Anulează",
        "cancel_transfer_button_short": "Anulează Transferul",
        "ok_continue_button": "OK, Continuă",
        "reject_button": "Refuză",
        "apply_and_reload_button": "Aplică și Reîncarcă",
        "apply_button": "Aplică",
        "apply_and_reload_tooltip": "Salvează limba și reîncarcă interfața pentru a aplica modificările.",
        "accept_button": "Acceptă",
        "add_button": "Adaugă",
        "revoke_button": "Revocă",

        # Send Page
        "send_files_title": "Trimite Fișiere",
        "connection_mode_title": "Mod de Conectare",
        "configure_connection_title": "Configurare Conexiune",
        "select_files_title": "Selectează Fișiere & Foldere",
        "discovery_mode_title": "Mod Descoperire",
        "send_mode_auto": "Mod Automat (LAN)",
        "send_mode_manual": "Mod Manual (LAN/WAN)",
        "send_mode_direct_ip": "IP Direct",
        "send_mode_subnet_scan": "Scanare Subrețea",
        "lan_selector_label": "Interfață de rețea",
        "lan_helper_text": "Valoarea implicită este adaptorul utilizat în prezent pentru accesul la internet.",
        "refresh_network_list_tooltip": "Reîmprospătează lista de rețele",
        "scan_for_receivers_button": "Scanează pentru receptori",
        "check_status_button": "Verifică Starea",
        "send_to_specific_ip_title": "Trimite la o adresă IP specifică (LAN sau WAN)",
        "receiver_ip_label": "Adresă IP Receptor",
        "receiver_ip_hint": "ex: 192.168.1.50 sau 2001:db8::1",
        "port_label": "Port",
        "send_to_ip_button": "Trimite la IP",
        "scan_subnet_title": "Scanează o subrețea pentru receptori",
        "subnet_scan_label": "Subrețea de Scanat (CIDR)",
        "subnet_scan_hint": "ex: 192.168.1.0/24",
        "what_is_this_tooltip": "Ce este asta?",
        "scan_subnet_button": "Scanează Subrețea",
        "stage_data_title": "Pregătește datele pentru transferul criptat",
        "add_files_button": "Adaugă Fișiere",
        "add_files_subtitle": "Selectează elemente individuale",
        "add_folders_button": "Adaugă Foldere",
        "add_folders_subtitle": "Selectează structuri de directoare întregi",
        "selected_file_none": "Niciun fișier sau folder selectat",
        "selected_file_count": "{count} element(e) pregătite pentru transfer:",
        "remove_from_list_tooltip": "Elimină din lista de transfer",
        "devices_ready_title": "Dispozitive gata să primească",
        "devices_ready_subtitle": "Se scanează rețeaua locală pentru alți receptori PY2PY.",
        "device_list_ip_prefix": "IP: {ip}",
        "device_list_send_button": "Trimite",

        # Receive Page
        "receive_files_title": "Primește fișiere",
        "listen_on_title": "Ascultă pentru fișiere primite pe",
        "restart_receiver_button": "Repornește Receptorul",
        "stop_receiver_button": "Oprește Receptorul",
        "network_settings_title": "Setări de Rețea",
        "listening_port_label": "Port de Ascultare",
        "wan_receive_info": "Pentru a primi fișiere de pe internet (WAN), trebuie să configurați routerul pentru a redirecționa portul TCP ales către IP-ul local al acestui dispozitiv. Utilizați modul de firewall 'Securitate Ridicată' sau 'Public'. Aceasta este o funcție avansată; procedați cu prudență.",
        "firewall_access_control_title": "Firewall / Control Acces",
        "firewall_access_control_subtitle": "Controlează ce dispozitive îți pot trimite fișiere. O repornire a receptorului este necesară pentru ca modificările să aibă efect.",
        "firewall_mode_lan": "Doar LAN (Implicit, Recomandat)",
        "firewall_mode_high_security": "Securitate Ridicată (Dispozitive de Încredere & Listă Albă)",
        "firewall_mode_public": "Permite Tuturor (Nerecomandat pentru Internet)",
        "high_security_panel_info": "Permite transferuri doar de la dispozitive pe care le-ai 'aprobat' sau de la IP-uri adăugate manual în lista albă de mai jos.",
        "lan_only_panel_info": "Permite orice dispozitiv din rețeaua ta locală privată (ex: WiFi-ul de acasă). Blochează conexiunile de pe internetul public.",
        "public_panel_info": "AVERTISMENT: Permite oricărui dispozitiv de oriunde, inclusiv de pe internetul public, să încerce un transfer de fișiere. Folosiți doar dacă înțelegeți riscurile.",
        "add_ip_whitelist_label": "Adaugă IP în Lista Albă",
        "add_ip_whitelist_hint": "ex: 192.168.1.100",

        # Trusted Devices Page
        "trusted_devices_title": "Dispozitive de încredere",
        "trusted_devices_subtitle": "Dispozitive pe care ai ales să le aprobi în timpul unui transfer. Poți revoca încrederea oricând.",
        "no_trusted_devices": "Niciun dispozitiv de încredere stocat.",
        "unnamed_device": "Dispozitiv fără nume",
        "fingerprint_label": "Amprentă: {fp}",
        "trusted_since_label": "De încredere din: {date}",
        "unknown_date": "Dată necunoscută",

        # Dialogs & Popups
        "transfer_complete_title": "Transfer finalizat",
        "transfer_complete_message": "{filename} a sosit cu succes.\nSalvat în: {location}",
        "verify_receiver_title": "Verifică receptorul",
        "verify_receiver_instructions": "Compară acest cod cu cel din dialogul de transfer al receptorului. Continuă doar dacă ambele coduri sunt identice.",
        "codes_match_button": "Codurile se potrivesc",
        "cancel_transfer_button": "Anulează transferul",
        "incoming_file_title": "Fișier în așteptare",
        "trust_device_checkbox": "Acordă încredere acestui dispozitiv (reține pentru transferuri viitoare)",
        "incoming_transfer_from": "Transfer de la {name} ({fp})",
        "filename_label": "Nume fișier: {filename}",
        "size_label": "Dimensiune: {size}",
        "compare_code_prompt": "Compară acest cod cu cel al expeditorului înainte de a accepta:",
        "verification_code_label": "Cod de verificare: {code}",
        "receiver_label": "Receptor: {name}",
        "receiver_identity_label": "Identitate receptor: {fp}",
        "win_firewall_title": "Windows Firewall",
        "win_firewall_prompt": "Pentru a descoperi dispozitive și a primi fișiere, PY2PY trebuie să adauge reguli în Windows Firewall. Acest lucru necesită permisiuni de administrator și poate declanșa o fereastră UAC.",
        "linux_firewall_title": "Configurare Firewall Linux",
        "linux_firewall_prompt": "Firewall-ul dvs. ar putea bloca conexiunile. Pentru a permite PY2PY să primească fișiere, poate fi necesar să rulați următoarea comandă(e) într-un terminal:",
        "subnet_help_title": "Scanarea unei Subrețele",
        "subnet_help_line1": "Această funcție este pentru utilizatori avansați în rețele complexe unde descoperirea automată (mDNS/Zeroconf) s-ar putea să nu funcționeze între subrețele.",
        "subnet_help_line2": "Introduceți un interval de rețea în notație CIDR pentru a efectua o scanare rapidă unicast pentru receptori PY2PY.",
        "subnet_help_examples": "Exemple:",
        "subnet_help_example1": "  • 192.168.100.0/24 (scanează de la 192.168.100.1 la .254)",
        "subnet_help_example2": "  • 2001:db8:abcd::/48 (scanează un interval mare IPv6)",
        "dialog_title_select_save_folder": "Selectează folderul pentru salvarea fișierelor primite",
        "dialog_title_select_send_folder": "Selectează un folder de trimis",
        "dialog_title_select_default_receive_folder": "Selectează folderul implicit de primire",

        # Status Messages
        "status_checking_peer_status": "Se verifică starea pentru {ip}:{port}...",
        "status_peer_online": "Peer-ul la {ip}:{port} este online și accesibil.",
        "status_peer_offline": "Peer-ul la {ip}:{port} este offline sau nu răspunde.",
        "status_checking_short": "Se verifică...",
        "status_online_short": "Online",
        "status_offline_short": "Offline",
        "status_invalid_short": "Invalid",
        "status_item_removed": "Element eliminat.",
        "status_skipped_not_exist": "Omis (nu există): {path}",
        "status_choose_receiver": "Alege un receptor pentru a începe transferul criptat.",
        "status_selection_cleared": "Selecție ștearsă.",
        "status_refreshing_interfaces": "Se reîmprospătează interfețele de rețea...",
        "status_interfaces_updated": "Interfețele de rețea au fost actualizate. Poate fi necesar să reporniți scanarea/recepția.",
        "status_transfer_cancelled": "Transfer anulat.",
        "status_transfer_cancelled_by_user": "Transfer anulat de utilizator.",
        "status_announcing_as_receiver": "Se anunță dispozitivul pe {ip}:{port} ca Receptor...",
        "status_stopping_announcement": "Se oprește anunțul...",
        "status_trusted_receiver": "Receptor de încredere detectat; se omite verificarea manuală.",
        "status_file_selection_cancelled": "Selecția fișierelor a fost anulată.",
        "status_folder_selection_cancelled": "Selecția folderului a fost anulată.",
        "status_transfer_in_progress": "Transfer deja în curs, vă rugăm așteptați.",
        "status_select_files_first": "Selectați mai întâi unul sau mai multe fișiere sau foldere.",
        "status_invalid_port": "Port invalid: {port}. Trebuie să fie între 1 și 65535.",
        "status_invalid_subnet_format": "Format subrețea invalid: {subnet}",
        "status_preparing_transfer": "Se pregătește transferul criptat...",
        "status_found_receiver_details": "Receptor găsit: {name} la {ip}:{port}",
        "status_requesting_firewall_perms": "Se solicită permisiuni pentru firewall... Vă rugăm acceptați fereastra UAC.",
        "status_firewall_not_configured": "Firewall-ul nu este configurat. Descoperirea și recepția pot eșua.",
        "status_receiver_disconnected": "Receptor deconectat: {name}",
        "status_enter_valid_sender_ip": "Introduceți o adresă IP validă pentru interfața expeditorului.",
        "status_scanning_on_target": "Se scanează pentru receptori pe {target}...",
        "status_enter_subnet": "Vă rugăm introduceți o subrețea de scanat.",
        "status_subnet_scan_complete": "Scanarea subrețelei a fost finalizată.",
        "status_scanning_subnet": "Se scanează subrețeaua {subnet} pe portul {port}...",
        "status_enter_valid_listen_ip": "Introduceți o adresă IP validă pe care să ascultați.",
        "status_receiver_start_failed": "Pornirea serverului receptor a eșuat.",
        "status_ready_to_receive_on": "Gata de primit pe {ip}:{port}.",
        "status_receiving_stopped": "Recepția oprită.",
        "status_listening_securely_on": "Ascultă securizat pe {addrs}",
        "status_incoming_connection": "Conexiune de la {ip}",
        "status_blocked_public_ip": "Conexiune de la IP public {ip} blocată de politica firewall 'Doar LAN'.",
        "status_blocked_invalid_ip": "Nu s-a putut valida IP-ul {ip}. Se blochează conexiunea.",
        "status_establishing_secure_connection": "Se stabilește conexiunea securizată…",
        "status_secure_channel_established": "Canal securizat stabilit.",
        "status_blocked_high_security": "Conexiune de la {ip} ({fp}) blocată de politica 'Securitate Ridicată' (nu este de încredere sau pe lista albă).",
        "status_transfer_rejected": "Transfer respins.",
        "status_receiving_file": "Se primește {filename}…",
        "status_verifying_unpacking": "Transfer primit. Se verifică și se despachetează...",
        "status_client_disconnected_normal": "Clientul s-a deconectat după transfer, ceea ce este normal.",
        "status_received_successfully": "S-a primit {filename} cu succes.",
        "status_restarting_receiver": "Se repornește receptorul...",
        "status_settings_saved_restart": "Setări salvate. Reporniți receptorul pentru a aplica.",
        "settings_saved_snackbar": "Setări salvate!",
        "status_transfer_failed": "Transfer eșuat: {error}",
        "all_interfaces_target": "toate interfețele",

        # Errors
        "error_ip_required": "IP-ul este obligatoriu",
        "error_invalid_port": "Port invalid",
        "error_subnet_required": "Subrețeaua este obligatorie",
        "error_invalid_ip": "Adresă IP invalidă",
        "error_invalid_port_range": "Port invalid (1024-65535)",
        "error_bind_failed": "Nu s-a putut asculta pe {ip}:{port}. Adresa s-ar putea să nu fie disponibilă sau să fie în uz.",

        # Progress Handler
        "role_sending": "Se trimite",
        "role_receiving": "Se primește",
        "progress_label": "{role}: {completed} din {total} ({percent:.0f}%) - {speed}",
        "progress_label_no_speed": "{role}: {completed} din {total} ({percent:.0f}%)",
    }
    _locales["ru"] = {
        "app_title": "PY2PY — Безопасный обмен файлами",
        "app_name_short": "PY2PY",
        "py2py_device_name": "Устройство PY2PY",
        "main_title": "Безопасный локальный обмен файлами",
        "main_subtitle": "Выберите, что вы хотите сделать.",
        "send_button": "Отправить файл",
        "receive_button": "Получить файлы",
        "trusted_button": "Управление доверенными устройствами",
        "settings_button": "Настройки",

        "settings_title": "Настройки приложения",
        "settings_language_label": "Язык",
        "settings_language_restart_hint": "Для полного применения изменений языка требуется перезапуск.",
        "settings_receive_location_label": "Папка для сохранения файлов",
        "settings_receive_mode_label": "Режим приёма",
        "settings_receive_mode_fixed": "Сохранять в указанную папку",
        "settings_receive_mode_ask": "Запрашивать место сохранения перед каждой передачей.",
        "settings_change_location_button": "Изменить папку",
        "settings_save_button": "Сохранить настройки",
        "settings_show_only_recommended_interfaces_label": "Показывать только рекомендуемые сетевые интерфейсы",
        "settings_show_only_recommended_interfaces_subtitle": "Если включено, в раскрывающемся списке сетей будут скрыты виртуальные или служебные адаптеры.",
        "settings_saved_message": "Настройки сохранены. Некоторые изменения вступят в силу после перезапуска.",

        # UI General
        "status_ready": "Готово",
        "clear_all_button": "Очистить всё",
        "got_it_button": "Понятно",
        "ignore_button": "Игнорировать",
        "open_folder_button": "Открыть папку",
        "cancel_button": "Отмена",
        "cancel_transfer_button_short": "Отменить передачу",
        "ok_continue_button": "ОК, продолжить",
        "reject_button": "Отклонить",
        "apply_and_reload_button": "Применить и перезапустить",
        "apply_button": "Применить",
        "apply_and_reload_tooltip": "Сохраняет язык и перезагружает интерфейс для применения изменений.",
        "accept_button": "Принять",
        "add_button": "Добавить",
        "revoke_button": "Отозвать",

        # Send Page
        "send_files_title": "Отправка файлов",
        "connection_mode_title": "Режим подключения",
        "configure_connection_title": "Настроить подключение",
        "select_files_title": "Выберите файлы и папки",
        "discovery_mode_title": "Режим обнаружения",
        "send_mode_auto": "Автоматический режим (LAN)",
        "send_mode_manual": "Ручной режим (LAN/WAN)",
        "send_mode_direct_ip": "Прямой IP",
        "send_mode_subnet_scan": "Сканирование подсети",
        "lan_selector_label": "Сетевой интерфейс",
        "lan_helper_text": "По умолчанию используется сетевой адаптер, через который осуществляется доступ в Интернет.",
        "refresh_network_list_tooltip": "Обновить список сетей",
        "scan_for_receivers_button": "Найти получателей",
        "check_status_button": "Проверить статус",
        "send_to_specific_ip_title": "Отправить на указанный IP-адрес (LAN или WAN)",
        "receiver_ip_label": "IP-адрес получателя",
        "receiver_ip_hint": "например: 192.168.1.50 или 2001:db8::1",
        "port_label": "Порт",
        "send_to_ip_button": "Отправить по IP",
        "scan_subnet_title": "Сканировать подсеть для поиска получателей",
        "subnet_scan_label": "Подсеть для сканирования (CIDR)",
        "subnet_scan_hint": "например: 192.168.1.0/24",
        "what_is_this_tooltip": "Что это?",
        "scan_subnet_button": "Сканировать подсеть",
        "stage_data_title": "Подготовьте данные для зашифрованной передачи",
        "add_files_button": "Добавить файлы",
        "add_files_subtitle": "Выберите отдельные файлы",
        "add_folders_button": "Добавить папки",
        "add_folders_subtitle": "Выберите целые структуры каталогов",
        "selected_file_none": "Файлы или папки не выбраны",
        "selected_file_count": "Подготовлено элементов для передачи: {count}",
        "remove_from_list_tooltip": "Удалить из списка передачи",
        "devices_ready_title": "Устройства, готовые принять файлы",
        "devices_ready_subtitle": "Сканирование локальной сети на наличие других получателей PY2PY.",
        "device_list_ip_prefix": "IP: {ip}",
        "device_list_send_button": "Отправить",

        # Receive Page
        "receive_files_title": "Получение файлов",
        "listen_on_title": "Ожидание входящих файлов на",
        "restart_receiver_button": "Перезапустить получатель",
        "stop_receiver_button": "Остановить получатель",
        "network_settings_title": "Сетевые настройки",
        "listening_port_label": "Порт прослушивания",
        "wan_receive_info": "Чтобы получать файлы через Интернет (WAN), необходимо настроить маршрутизатор на переадресацию выбранного TCP-порта на локальный IP-адрес этого устройства. Используйте режим брандмауэра «Высокая безопасность» или «Общедоступный». Это расширенная функция — используйте её с осторожностью.",
        "firewall_access_control_title": "Брандмауэр / Контроль доступа",
        "firewall_access_control_subtitle": "Определяет, какие устройства могут отправлять вам файлы. Для применения изменений необходимо перезапустить получатель.",
        "firewall_mode_lan": "Только LAN (по умолчанию, рекомендуется)",
        "firewall_mode_high_security": "Высокая безопасность (доверенные устройства и белый список)",
        "firewall_mode_public": "Разрешить всем (не рекомендуется для Интернета)",
        "high_security_panel_info": "Разрешает передачу только от устройств, которым вы доверяете, или от IP-адресов, добавленных в белый список.",
        "lan_only_panel_info": "Разрешает передачу от любых устройств в вашей локальной сети (например, домашний Wi-Fi). Подключения из Интернета блокируются.",
        "public_panel_info": "ВНИМАНИЕ: Разрешает любому устройству, включая устройства из Интернета, пытаться отправить вам файлы. Используйте этот режим только если понимаете связанные риски.",
        "add_ip_whitelist_label": "Добавить IP в белый список",
        "add_ip_whitelist_hint": "например: 192.168.1.100",

        # Trusted Devices Page
        "trusted_devices_title": "Доверенные устройства",
        "trusted_devices_subtitle": "Устройства, которым вы доверили передачу файлов. Доверие можно отозвать в любой момент.",
        "no_trusted_devices": "Нет сохранённых доверенных устройств.",
        "unnamed_device": "Безымянное устройство",
        "fingerprint_label": "Отпечаток: {fp}",
        "trusted_since_label": "Доверено с: {date}",
        "unknown_date": "Дата неизвестна",

        # Dialogs & Popups
        "transfer_complete_title": "Передача завершена",
        "transfer_complete_message": "{filename} успешно получен.\nСохранён в: {location}",
        "verify_receiver_title": "Проверка получателя",
        "verify_receiver_instructions": "Сравните этот код с кодом, отображаемым на устройстве получателя. Продолжайте только если оба кода совпадают.",
        "codes_match_button": "Коды совпадают",
        "cancel_transfer_button": "Отменить передачу",
        "incoming_file_title": "Ожидающий файл",
        "trust_device_checkbox": "Доверять этому устройству (запомнить для будущих передач)",
        "incoming_transfer_from": "Передача от {name} ({fp})",
        "filename_label": "Имя файла: {filename}",
        "size_label": "Размер: {size}",
        "compare_code_prompt": "Перед подтверждением сравните этот код с кодом отправителя:",
        "verification_code_label": "Код проверки: {code}",
        "receiver_label": "Получатель: {name}",
        "receiver_identity_label": "Идентификатор получателя: {fp}",
        "win_firewall_title": "Брандмауэр Windows",
        "win_firewall_prompt": "Для обнаружения устройств и получения файлов PY2PY необходимо добавить правила в брандмауэр Windows. Для этого потребуются права администратора и может появиться окно UAC.",
        "linux_firewall_title": "Настройка брандмауэра Linux",
        "linux_firewall_prompt": "Ваш брандмауэр может блокировать соединения. Чтобы разрешить PY2PY получать файлы, вам может потребоваться выполнить следующую команду(ы) в терминале:",
        "subnet_help_title": "Сканирование подсети",
        "subnet_help_line1": "Эта функция предназначена для опытных пользователей в сложных сетях, где автоматическое обнаружение (mDNS/Zeroconf) может не работать между подсетями.",
        "subnet_help_line2": "Введите диапазон сети в формате CIDR, чтобы выполнить быстрое одноадресное сканирование на наличие получателей PY2PY.",
        "subnet_help_examples": "Примеры:",
        "subnet_help_example1": "  • 192.168.100.0/24 (сканирует адреса от 192.168.100.1 до .254)",
        "subnet_help_example2": "  • 2001:db8:abcd::/48 (сканирует большой диапазон IPv6)",
        "dialog_title_select_save_folder": "Выберите папку для сохранения полученных файлов",
        "dialog_title_select_send_folder": "Выберите папку для отправки",
        "dialog_title_select_default_receive_folder": "Выберите папку по умолчанию для сохранения файлов",

        # Status Messages
        "status_checking_peer_status": "Проверка статуса {ip}:{port}...",
        "status_peer_online": "Узел по адресу {ip}:{port} в сети и доступен.",
        "status_peer_offline": "Узел по адресу {ip}:{port} не в сети или не отвечает.",
        "status_checking_short": "Проверка...",
        "status_online_short": "В сети",
        "status_offline_short": "Не в сети",
        "status_invalid_short": "Неверно",
        "status_item_removed": "Элемент удалён.",
        "status_skipped_not_exist": "Пропущено (не существует): {path}",
        "status_choose_receiver": "Выберите получателя для начала защищённой передачи.",
        "status_selection_cleared": "Выбор очищен.",
        "status_refreshing_interfaces": "Обновление сетевых интерфейсов...",
        "status_interfaces_updated": "Сетевые интерфейсы обновлены. Может потребоваться повторный запуск поиска или получения.",
        "status_transfer_cancelled": "Передача отменена.",
        "status_transfer_cancelled_by_user": "Передача отменена пользователем.",
        "status_announcing_as_receiver": "Объявление устройства на {ip}:{port} как Получателя...",
        "status_stopping_announcement": "Остановка объявления...",
        "status_trusted_receiver": "Обнаружен доверенный получатель; ручная проверка пропущена.",
        "status_file_selection_cancelled": "Выбор файлов отменён.",
        "status_folder_selection_cancelled": "Выбор папки отменён.",
        "status_transfer_in_progress": "Передача уже выполняется. Пожалуйста, подождите.",
        "status_select_files_first": "Сначала выберите один или несколько файлов либо папок.",
        "status_invalid_port": "Недопустимый порт: {port}. Допустимый диапазон: 1–65535.",
        "status_invalid_subnet_format": "Неверный формат подсети: {subnet}",
        "status_preparing_transfer": "Подготовка защищённой передачи...",
        "status_found_receiver_details": "Найден получатель: {name} по адресу {ip}:{port}",
        "status_requesting_firewall_perms": "Запрашиваются разрешения для брандмауэра... Пожалуйста, подтвердите окно UAC.",
        "status_firewall_not_configured": "Брандмауэр не настроен. Обнаружение устройств и получение файлов могут не работать.",
        "status_receiver_disconnected": "Получатель отключён: {name}",
        "status_enter_valid_sender_ip": "Введите корректный IP-адрес для интерфейса отправителя.",
        "status_scanning_on_target": "Поиск получателей на {target}...",
        "status_enter_subnet": "Введите подсеть для сканирования.",
        "status_subnet_scan_complete": "Сканирование подсети завершено.",
        "status_scanning_subnet": "Сканирование подсети {subnet} через порт {port}...",
        "status_enter_valid_listen_ip": "Введите корректный IP-адрес для прослушивания.",
        "status_receiver_start_failed": "Не удалось запустить сервер получателя.",
        "status_ready_to_receive_on": "Готов к приёму на {ip}:{port}.",
        "status_receiving_stopped": "Приём остановлен.",
        "status_listening_securely_on": "Безопасное прослушивание на {addrs}",
        "status_incoming_connection": "Входящее соединение от {ip}",
        "status_blocked_public_ip": "Соединение с публичного IP {ip} заблокировано политикой брандмауэра 'Только LAN'.",
        "status_blocked_invalid_ip": "Не удалось проверить IP {ip}. Соединение заблокировано.",
        "status_establishing_secure_connection": "Установка защищённого соединения…",
        "status_secure_channel_established": "Защищённый канал установлен.",
        "status_blocked_high_security": "Соединение от {ip} ({fp}) заблокировано политикой 'Высокая безопасность' (не доверено или не в белом списке).",
        "status_transfer_rejected": "Передача отклонена.",
        "status_receiving_file": "Получение {filename}…",
        "status_verifying_unpacking": "Передача получена. Проверка и распаковка...",
        "status_client_disconnected_normal": "Клиент отключился после передачи, что является нормой.",
        "status_received_successfully": "Файл {filename} успешно получен.",
        "status_restarting_receiver": "Перезапуск получателя...",
        "status_settings_saved_restart": "Настройки сохранены. Перезапустите получатель для применения изменений.",
        "settings_saved_snackbar": "Настройки сохранены!",
        "status_transfer_failed": "Передача не удалась: {error}",
        "all_interfaces_target": "все интерфейсы",

        # Errors
        "error_ip_required": "Требуется IP-адрес",
        "error_invalid_port": "Недопустимый порт",
        "error_subnet_required": "Требуется подсеть",
        "error_invalid_ip": "Недопустимый IP-адрес",
        "error_invalid_port_range": "Недопустимый порт (1024–65535)",
        "error_bind_failed": "Не удалось начать прослушивание на {ip}:{port}. Адрес может быть недоступен или уже используется.",

        # Progress Handler
        "role_sending": "Отправка",
        "role_receiving": "Получение",
        "progress_label": "{role}: {completed} из {total} ({percent:.0f}%) — {speed}",
        "progress_label_no_speed": "{role}: {completed} из {total} ({percent:.0f}%)",
    }
    _locales["de"] = {
        "app_title": "PY2PY – Sicherer Dateiaustausch",
        "app_name_short": "PY2PY",
        "py2py_device_name": "PY2PY-Gerät",
        "main_title": "Sicherer lokaler Dateiaustausch",
        "main_subtitle": "Wählen Sie aus, was Sie tun möchten.",
        "send_button": "Datei senden",
        "receive_button": "Dateien empfangen",
        "trusted_button": "Vertrauenswürdige Geräte verwalten",
        "settings_button": "Einstellungen",
        "settings_title": "Anwendungseinstellungen",
        "settings_language_label": "Sprache",
        "settings_language_restart_hint": "Ein Neustart ist erforderlich, um die Sprachänderungen vollständig zu übernehmen.",
        "settings_receive_location_label": "Speicherort für empfangene Dateien",
        "settings_receive_mode_label": "Empfangsmodus",
        "settings_receive_mode_fixed": "An einem festen Ort speichern",
        "settings_receive_mode_ask": "Bei jeder Übertragung nach dem Speicherort fragen",
        "settings_change_location_button": "Speicherort ändern",
        "settings_save_button": "Einstellungen speichern",
        "settings_show_only_recommended_interfaces_label": "Nur empfohlene Netzwerkschnittstellen anzeigen",
        "settings_show_only_recommended_interfaces_subtitle": "Wenn aktiviert, blendet das Netzwerk-Dropdown virtuelle oder spezielle Adapter aus.",
        "settings_saved_message": "Einstellungen gespeichert. Einige Änderungen erfordern möglicherweise einen Neustart.",

        # UI Allgemein
        "status_ready": "Bereit",
        "clear_all_button": "Alles löschen",
        "got_it_button": "Verstanden",
        "ignore_button": "Ignorieren",
        "open_folder_button": "Ordner öffnen",
        "cancel_button": "Abbrechen",
        "cancel_transfer_button_short": "Übertragung abbrechen",
        "ok_continue_button": "OK, Weiter",
        "reject_button": "Ablehnen",
        "apply_and_reload_button": "Anwenden & Neu laden",
        "apply_button": "Anwenden",
        "apply_and_reload_tooltip": "Speichert die Sprache und lädt die Benutzeroberfläche neu, um die Änderungen zu übernehmen.",
        "accept_button": "Akzeptieren",
        "add_button": "Hinzufügen",
        "revoke_button": "Widerrufen",

        # Senden-Seite
        "send_files_title": "Dateien senden",
        "connection_mode_title": "Verbindungsmodus",
        "configure_connection_title": "Verbindung konfigurieren",
        "select_files_title": "Dateien & Ordner auswählen",
        "discovery_mode_title": "Entdeckungsmodus",
        "send_mode_auto": "Auto-Modus (LAN)",
        "send_mode_manual": "Manueller Modus (LAN/WAN)",
        "send_mode_direct_ip": "Direkte IP",
        "send_mode_subnet_scan": "Subnetz-Scan",
        "lan_selector_label": "Netzwerkschnittstelle",
        "lan_helper_text": "Standard ist der Adapter, der aktuell für den Internetzugang verwendet wird.",
        "refresh_network_list_tooltip": "Netzwerkliste aktualisieren",
        "scan_for_receivers_button": "Nach Empfängern suchen",
        "check_status_button": "Status prüfen",
        "send_to_specific_ip_title": "An eine bestimmte IP-Adresse senden (LAN oder WAN)",
        "receiver_ip_label": "Empfänger-IP-Adresse",
        "receiver_ip_hint": "z.B. 192.168.1.50 oder 2001:db8::1",
        "port_label": "Port",
        "send_to_ip_button": "An IP senden",
        "scan_subnet_title": "Ein Subnetz nach Empfängern durchsuchen",
        "subnet_scan_label": "Zu scannendes Subnetz (CIDR)",
        "subnet_scan_hint": "z.B. 192.168.1.0/24",
        "what_is_this_tooltip": "Was ist das?",
        "scan_subnet_button": "Subnetz scannen",
        "stage_data_title": "Daten für verschlüsselte Übertragung vorbereiten",
        "add_files_button": "Dateien hinzufügen",
        "add_files_subtitle": "Einzelne Elemente auswählen",
        "add_folders_button": "Ordner hinzufügen",
        "add_folders_subtitle": "Ganze Verzeichnisstrukturen auswählen",
        "selected_file_none": "Keine Dateien oder Ordner ausgewählt",
        "selected_file_count": "{count} Element(e) für die Übertragung vorbereitet:",
        "remove_from_list_tooltip": "Aus der Übertragungsliste entfernen",
        "devices_ready_title": "Geräte bereit zum Empfangen",
        "devices_ready_subtitle": "Durchsucht Ihr lokales Netzwerk nach anderen PY2PY-Empfängern.",
        "device_list_ip_prefix": "IP: {ip}",
        "device_list_send_button": "Senden",

        # Empfangen-Seite
        "receive_files_title": "Dateien empfangen",
        "listen_on_title": "Auf eingehende Dateien warten auf",
        "restart_receiver_button": "Empfänger neu starten",
        "stop_receiver_button": "Empfänger anhalten",
        "network_settings_title": "Netzwerkeinstellungen",
        "listening_port_label": "Listening-Port",
        "wan_receive_info": "Um Dateien aus dem Internet (WAN) zu empfangen, müssen Sie Ihren Router so konfigurieren, dass der gewählte TCP-Port an die lokale IP dieses Geräts weitergeleitet wird. Verwenden Sie den Firewall-Modus 'Hohe Sicherheit' oder 'Öffentlich'. Dies ist eine erweiterte Funktion; gehen Sie mit Vorsicht vor.",
        "firewall_access_control_title": "Firewall / Zugriffskontrolle",
        "firewall_access_control_subtitle": "Steuern Sie, welche Geräte Ihnen Dateien senden können. Ein Neustart des Empfängers ist erforderlich, damit die Änderungen wirksam werden.",
        "firewall_mode_lan": "Nur LAN (Standard, empfohlen)",
        "firewall_mode_high_security": "Hohe Sicherheit (Vertrauenswürdige Geräte & Whitelist)",
        "firewall_mode_public": "Jedem erlauben (Unsicher für das Internet)",
        "high_security_panel_info": "Erlaubt nur Übertragungen von Geräten, denen Sie 'vertrauen' oder von IPs, die Sie manuell zur Whitelist hinzufügen.",
        "lan_only_panel_info": "Erlaubt jedem Gerät in Ihrem lokalen privaten Netzwerk (z.B. Ihr Heim-WLAN). Blockiert Verbindungen aus dem öffentlichen Internet.",
        "public_panel_info": "WARNUNG: Erlaubt jedem Gerät von überall, einschließlich dem öffentlichen Internet, eine Dateiübertragung zu versuchen. Nur verwenden, wenn Sie die Risiken verstehen.",
        "add_ip_whitelist_label": "IP zur Whitelist hinzufügen",
        "add_ip_whitelist_hint": "z.B. 192.168.1.100",

        # Vertrauenswürdige Geräte Seite
        "trusted_devices_title": "Vertrauenswürdige Geräte",
        "trusted_devices_subtitle": "Geräte, denen Sie während einer Übertragung Ihr Vertrauen ausgesprochen haben. Sie können das Vertrauen jederzeit widerrufen.",
        "no_trusted_devices": "Keine vertrauenswürdigen Geräte gespeichert.",
        "unnamed_device": "Unbenanntes Gerät",
        "fingerprint_label": "Fingerabdruck: {fp}",
        "trusted_since_label": "Vertrauenswürdig seit: {date}",
        "unknown_date": "Unbekanntes Datum",

        # Dialoge & Popups
        "transfer_complete_title": "Übertragung abgeschlossen",
        "transfer_complete_message": "{filename} erfolgreich angekommen.\nGespeichert in: {location}",
        "verify_receiver_title": "Empfänger überprüfen",
        "verify_receiver_instructions": "Vergleichen Sie diesen Code mit dem im Dialog des Empfängers. Fahren Sie nur fort, wenn beide Codes identisch sind.",
        "codes_match_button": "Codes stimmen überein",
        "cancel_transfer_button": "Übertragung abbrechen",
        "incoming_file_title": "Eingehende Datei",
        "trust_device_checkbox": "Diesem Gerät vertrauen (für zukünftige Übertragungen merken)",
        "incoming_transfer_from": "Eingehende Übertragung von {name} ({fp})",
        "filename_label": "Dateiname: {filename}",
        "size_label": "Größe: {size}",
        "compare_code_prompt": "Vergleichen Sie diesen Code mit dem des Absenders, bevor Sie akzeptieren:",
        "verification_code_label": "Verifizierungscode: {code}",
        "receiver_label": "Empfänger: {name}",
        "receiver_identity_label": "Empfängeridentität: {fp}",
        "win_firewall_title": "Windows-Firewall",
        "win_firewall_prompt": "Um Geräte zu erkennen und Dateien zu empfangen, muss PY2PY Regeln zur Windows-Firewall hinzufügen. Dies erfordert Administratorrechte und kann eine UAC-Aufforderung auslösen.",
        "linux_firewall_title": "Linux-Firewall-Konfiguration",
        "linux_firewall_prompt": "Ihre Firewall blockiert möglicherweise Verbindungen. Um PY2PY den Empfang von Dateien zu ermöglichen, müssen Sie möglicherweise den/die folgenden Befehl(e) in einem Terminal ausführen:",
        "subnet_help_title": "Scannen eines Subnetzes",
        "subnet_help_line1": "Diese Funktion ist für fortgeschrittene Benutzer in komplexen Netzwerken gedacht, in denen die automatische Erkennung (mDNS/Zeroconf) möglicherweise nicht über Subnetze hinweg funktioniert.",
        "subnet_help_line2": "Geben Sie einen Netzwerkbereich in CIDR-Notation ein, um einen schnellen Unicast-Scan nach PY2PY-Empfängern durchzuführen.",
        "subnet_help_examples": "Beispiele:",
        "subnet_help_example1": "  • 192.168.100.0/24 (scannt 192.168.100.1 bis .254)",
        "subnet_help_example2": "  • 2001:db8:abcd::/48 (scannt einen großen IPv6-Bereich)",
        "dialog_title_select_save_folder": "Ordner zum Speichern empfangener Dateien auswählen",
        "dialog_title_select_send_folder": "Einen Ordner zum Senden auswählen",
        "dialog_title_select_default_receive_folder": "Standard-Empfangsordner auswählen",

        # Statusmeldungen
        "status_checking_peer_status": "Prüfe Status von {ip}:{port}...",
        "status_peer_online": "Peer unter {ip}:{port} ist online und erreichbar.",
        "status_peer_offline": "Peer unter {ip}:{port} ist offline oder antwortet nicht.",
        "status_checking_short": "Prüfe...",
        "status_online_short": "Online",
        "status_offline_short": "Offline",
        "status_invalid_short": "Ungültig",
        "status_item_removed": "Element entfernt.",
        "status_skipped_not_exist": "Übersprungen (existiert nicht): {path}",
        "status_choose_receiver": "Wählen Sie einen Empfänger, um die verschlüsselte Übertragung zu starten.",
        "status_selection_cleared": "Auswahl gelöscht.",
        "status_refreshing_interfaces": "Netzwerkschnittstellen werden aktualisiert...",
        "status_interfaces_updated": "Netzwerkschnittstellen aktualisiert. Möglicherweise müssen Sie das Scannen/Empfangen neu starten.",
        "status_transfer_cancelled": "Übertragung abgebrochen.",
        "status_transfer_cancelled_by_user": "Übertragung vom Benutzer abgebrochen.",
        "status_announcing_as_receiver": "Gerät auf {ip}:{port} wird als Empfänger angekündigt...",
        "status_stopping_announcement": "Ankündigung wird gestoppt...",
        "status_trusted_receiver": "Vertrauenswürdiger Empfänger erkannt; manuelle Überprüfung wird übersprungen.",
        "status_file_selection_cancelled": "Dateiauswahl abgebrochen.",
        "status_folder_selection_cancelled": "Ordnerauswahl abgebrochen.",
        "status_transfer_in_progress": "Übertragung läuft bereits, bitte warten.",
        "status_select_files_first": "Wählen Sie zuerst eine oder mehrere Dateien oder Ordner aus.",
        "status_invalid_port": "Ungültiger Port: {port}. Muss zwischen 1 und 65535 liegen.",
        "status_invalid_subnet_format": "Ungültiges Subnetzformat: {subnet}",
        "status_preparing_transfer": "Verschlüsselte Übertragung wird vorbereitet...",
        "status_found_receiver_details": "Empfänger gefunden: {name} bei {ip}:{port}",
        "status_requesting_firewall_perms": "Firewall-Berechtigungen werden angefordert... Bitte akzeptieren Sie die UAC-Aufforderung.",
        "status_firewall_not_configured": "Firewall nicht konfiguriert. Erkennung und Empfang können fehlschlagen.",
        "status_receiver_disconnected": "Empfänger getrennt: {name}",
        "status_enter_valid_sender_ip": "Geben Sie eine gültige IP-Adresse für die Senderschnittstelle ein.",
        "status_scanning_on_target": "Suche nach Empfängern auf {target}...",
        "status_enter_subnet": "Bitte geben Sie ein zu scannendes Subnetz ein.",
        "status_subnet_scan_complete": "Subnetz-Scan abgeschlossen.",
        "status_scanning_subnet": "Scanne Subnetz {subnet} auf Port {port}...",
        "status_enter_valid_listen_ip": "Geben Sie eine gültige IP-Adresse zum Lauschen ein.",
        "status_receiver_start_failed": "Starten des Empfängerservers fehlgeschlagen.",
        "status_ready_to_receive_on": "Bereit zum Empfangen auf {ip}:{port}.",
        "status_receiving_stopped": "Empfang gestoppt.",
        "status_listening_securely_on": "Sicheres Lauschen auf {addrs}",
        "status_incoming_connection": "Eingehende Verbindung von {ip}",
        "status_blocked_public_ip": "Verbindung von öffentlicher IP {ip} durch 'Nur LAN'-Firewall-Richtlinie blockiert.",
        "status_blocked_invalid_ip": "IP {ip} konnte nicht validiert werden. Verbindung wird blockiert.",
        "status_establishing_secure_connection": "Sichere Verbindung wird hergestellt…",
        "status_secure_channel_established": "Sicherer Kanal hergestellt.",
        "status_blocked_high_security": "Verbindung von {ip} ({fp}) durch 'Hohe Sicherheit'-Richtlinie blockiert (nicht vertrauenswürdig oder auf Whitelist).",
        "status_transfer_rejected": "Übertragung abgelehnt.",
        "status_receiving_file": "Empfange {filename}…",
        "status_verifying_unpacking": "Übertragung empfangen. Überprüfe und entpacke...",
        "status_client_disconnected_normal": "Client hat sich nach der Übertragung getrennt, was normal ist.",
        "status_received_successfully": "{filename} erfolgreich empfangen.",
        "status_restarting_receiver": "Empfänger wird neu gestartet...",
        "status_settings_saved_restart": "Einstellungen gespeichert. Starten Sie den Empfänger neu, um sie zu übernehmen.",
        "settings_saved_snackbar": "Einstellungen gespeichert!",
        "status_transfer_failed": "Übertragung fehlgeschlagen: {error}",
        "all_interfaces_target": "allen Schnittstellen",

        # Fehler
        "error_ip_required": "IP ist erforderlich",
        "error_invalid_port": "Ungültiger Port",
        "error_subnet_required": "Subnetz ist erforderlich",
        "error_invalid_ip": "Ungültige IP-Adresse",
        "error_invalid_port_range": "Ungültiger Port (1024-65535)",
        "error_bind_failed": "Lauschen auf {ip}:{port} fehlgeschlagen. Die Adresse ist möglicherweise nicht verfügbar oder wird bereits verwendet.",

        # Fortschrittsanzeige
        "role_sending": "Senden",
        "role_receiving": "Empfangen",
        "progress_label": "{role}: {completed} von {total} ({percent:.0f}%) - {speed}",
        "progress_label_no_speed": "{role}: {completed} von {total} ({percent:.0f}%)",
    }
    _locales["fr"] = {
        "app_title": "PY2PY — Partage de fichiers sécurisé",
        "app_name_short": "PY2PY",
        "py2py_device_name": "Appareil PY2PY",
        "main_title": "Partage de fichiers local et sécurisé",
        "main_subtitle": "Choisissez ce que vous voulez faire.",
        "send_button": "Envoyer un fichier",
        "receive_button": "Recevoir des fichiers",
        "trusted_button": "Gérer les appareils de confiance",
        "settings_button": "Paramètres",
        "settings_title": "Paramètres de l'application",
        "settings_language_label": "Langue",
        "settings_language_restart_hint": "Un redémarrage est nécessaire pour appliquer entièrement les changements de langue.",
        "settings_receive_location_label": "Emplacement de réception des fichiers",
        "settings_receive_mode_label": "Mode de réception",
        "settings_receive_mode_fixed": "Enregistrer à un emplacement fixe",
        "settings_receive_mode_ask": "Demander où enregistrer pour chaque transfert",
        "settings_change_location_button": "Changer l'emplacement",
        "settings_save_button": "Enregistrer les paramètres",
        "settings_show_only_recommended_interfaces_label": "Afficher uniquement les interfaces réseau recommandées",
        "settings_show_only_recommended_interfaces_subtitle": "Lorsque cette option est activée, le menu déroulant du réseau masquera les adaptateurs virtuels ou à usage spécial.",
        "settings_saved_message": "Paramètres enregistrés. Certains changements peuvent nécessiter un redémarrage.",

        # UI Général
        "status_ready": "Prêt",
        "clear_all_button": "Tout effacer",
        "got_it_button": "Compris",
        "ignore_button": "Ignorer",
        "open_folder_button": "Ouvrir le dossier",
        "cancel_button": "Annuler",
        "cancel_transfer_button_short": "Annuler le Transfert",
        "ok_continue_button": "OK, Continuer",
        "reject_button": "Rejeter",
        "apply_and_reload_button": "Appliquer & Recharger",
        "apply_button": "Appliquer",
        "apply_and_reload_tooltip": "Enregistre la langue et recharge l'interface utilisateur pour appliquer les changements.",
        "accept_button": "Accepter",
        "add_button": "Ajouter",
        "revoke_button": "Révoquer",

        # Page d'envoi
        "send_files_title": "Envoyer des fichiers",
        "connection_mode_title": "Mode de connexion",
        "configure_connection_title": "Configurer la connexion",
        "select_files_title": "Sélectionner des fichiers et des dossiers",
        "discovery_mode_title": "Mode de découverte",
        "send_mode_auto": "Mode Auto (LAN)",
        "send_mode_manual": "Mode Manuel (LAN/WAN)",
        "send_mode_direct_ip": "IP Directe",
        "send_mode_subnet_scan": "Scan de sous-réseau",
        "lan_selector_label": "Interface réseau",
        "lan_helper_text": "La valeur par défaut est l'adaptateur actuellement utilisé pour l'accès à Internet.",
        "refresh_network_list_tooltip": "Actualiser la liste des réseaux",
        "scan_for_receivers_button": "Rechercher des récepteurs",
        "check_status_button": "Vérifier le statut",
        "send_to_specific_ip_title": "Envoyer à une adresse IP spécifique (LAN ou WAN)",
        "receiver_ip_label": "Adresse IP du récepteur",
        "receiver_ip_hint": "ex: 192.168.1.50 ou 2001:db8::1",
        "port_label": "Port",
        "send_to_ip_button": "Envoyer à l'IP",
        "scan_subnet_title": "Scanner un sous-réseau pour trouver des récepteurs",
        "subnet_scan_label": "Sous-réseau à scanner (CIDR)",
        "subnet_scan_hint": "ex: 192.168.1.0/24",
        "what_is_this_tooltip": "Qu'est-ce que c'est ?",
        "scan_subnet_button": "Scanner le sous-réseau",
        "stage_data_title": "Préparer les données pour un transfert chiffré",
        "add_files_button": "Ajouter des fichiers",
        "add_files_subtitle": "Sélectionner des éléments individuels",
        "add_folders_button": "Ajouter des dossiers",
        "add_folders_subtitle": "Sélectionner des arborescences de répertoires entières",
        "selected_file_none": "Aucun fichier ou dossier sélectionné",
        "selected_file_count": "{count} élément(s) préparé(s) pour le transfert :",
        "remove_from_list_tooltip": "Retirer de la liste de transfert",
        "devices_ready_title": "Appareils prêts à recevoir",
        "devices_ready_subtitle": "Analyse de votre réseau local à la recherche d'autres récepteurs PY2PY.",
        "device_list_ip_prefix": "IP : {ip}",
        "device_list_send_button": "Envoyer",

        # Page de réception
        "receive_files_title": "Recevoir des fichiers",
        "listen_on_title": "Écouter les fichiers entrants sur",
        "restart_receiver_button": "Redémarrer le récepteur",
        "stop_receiver_button": "Arrêter le récepteur",
        "network_settings_title": "Paramètres réseau",
        "listening_port_label": "Port d'écoute",
        "wan_receive_info": "Pour recevoir des fichiers depuis Internet (WAN), vous devez configurer votre routeur pour rediriger le port TCP choisi vers l'IP locale de cet appareil. Utilisez le mode pare-feu 'Haute sécurité' ou 'Public'. Ceci est une fonctionnalité avancée ; procédez avec prudence.",
        "firewall_access_control_title": "Pare-feu / Contrôle d'accès",
        "firewall_access_control_subtitle": "Contrôlez quels appareils peuvent vous envoyer des fichiers. Un redémarrage du récepteur est nécessaire pour que les modifications prennent effet.",
        "firewall_mode_lan": "LAN uniquement (Par défaut, Recommandé)",
        "firewall_mode_high_security": "Haute sécurité (Appareils de confiance & Liste blanche)",
        "firewall_mode_public": "Autoriser tout le monde (Non sécurisé pour Internet)",
        "high_security_panel_info": "N'autorise que les transferts depuis des appareils que vous avez 'approuvés' ou des IP que vous ajoutez manuellement à la liste blanche ci-dessous.",
        "lan_only_panel_info": "Autorise tout appareil sur votre réseau privé local (par ex. votre Wi-Fi domestique). Bloque les connexions depuis l'internet public.",
        "public_panel_info": "AVERTISSEMENT : Autorise n'importe quel appareil, de n'importe où, y compris l'internet public, à tenter un transfert de fichiers. N'utilisez que si vous comprenez les risques.",
        "add_ip_whitelist_label": "Ajouter une IP à la liste blanche",
        "add_ip_whitelist_hint": "ex: 192.168.1.100",

        # Page des appareils de confiance
        "trusted_devices_title": "Appareils de confiance",
        "trusted_devices_subtitle": "Appareils auxquels vous avez choisi de faire confiance lors d'un transfert. Vous pouvez révoquer la confiance à tout moment.",
        "no_trusted_devices": "Aucun appareil de confiance enregistré.",
        "unnamed_device": "Appareil sans nom",
        "fingerprint_label": "Empreinte : {fp}",
        "trusted_since_label": "De confiance depuis : {date}",
        "unknown_date": "Date inconnue",

        # Dialogues & Popups
        "transfer_complete_title": "Transfert terminé",
        "transfer_complete_message": "{filename} est arrivé avec succès.\nEnregistré dans : {location}",
        "verify_receiver_title": "Vérifier le récepteur",
        "verify_receiver_instructions": "Comparez ce code avec celui de la boîte de dialogue de transfert entrant du récepteur. Ne continuez que si les deux codes sont identiques.",
        "codes_match_button": "Les codes correspondent",
        "cancel_transfer_button": "Annuler le transfert",
        "incoming_file_title": "Fichier entrant",
        "trust_device_checkbox": "Faire confiance à cet appareil (mémoriser pour les futurs transferts)",
        "incoming_transfer_from": "Transfert entrant de {name} ({fp})",
        "filename_label": "Nom du fichier : {filename}",
        "size_label": "Taille : {size}",
        "compare_code_prompt": "Comparez ce code avec celui de l'expéditeur avant d'accepter :",
        "verification_code_label": "Code de vérification : {code}",
        "receiver_label": "Récepteur : {name}",
        "receiver_identity_label": "Identité du récepteur : {fp}",
        "win_firewall_title": "Pare-feu Windows",
        "win_firewall_prompt": "Pour découvrir des appareils et recevoir des fichiers, PY2PY doit ajouter des règles au Pare-feu Windows. Cela nécessite des autorisations d'administrateur et peut déclencher une invite UAC.",
        "linux_firewall_title": "Configuration du pare-feu Linux",
        "linux_firewall_prompt": "Votre pare-feu bloque peut-être les connexions. Pour autoriser PY2PY à recevoir des fichiers, vous devrez peut-être exécuter la ou les commandes suivantes dans un terminal :",
        "subnet_help_title": "Scan d'un sous-réseau",
        "subnet_help_line1": "Cette fonctionnalité est destinée aux utilisateurs avancés sur des réseaux complexes où la découverte automatique (mDNS/Zeroconf) peut ne pas fonctionner entre les sous-réseaux.",
        "subnet_help_line2": "Entrez une plage réseau en notation CIDR pour effectuer un scan unicast rapide des récepteurs PY2PY.",
        "subnet_help_examples": "Exemples :",
        "subnet_help_example1": "  • 192.168.100.0/24 (scanne de 192.168.100.1 à .254)",
        "subnet_help_example2": "  • 2001:db8:abcd::/48 (scanne une large plage IPv6)",
        "dialog_title_select_save_folder": "Sélectionner le dossier pour enregistrer les fichiers reçus",
        "dialog_title_select_send_folder": "Sélectionner un dossier à envoyer",
        "dialog_title_select_default_receive_folder": "Sélectionner le dossier de réception par défaut",

        # Messages de statut
        "status_checking_peer_status": "Vérification du statut de {ip}:{port}...",
        "status_peer_online": "Le pair à {ip}:{port} est en ligne et joignable.",
        "status_peer_offline": "Le pair à {ip}:{port} est hors ligne ou ne répond pas.",
        "status_checking_short": "Vérification...",
        "status_online_short": "En ligne",
        "status_offline_short": "Hors ligne",
        "status_invalid_short": "Invalide",
        "status_item_removed": "Élément retiré.",
        "status_skipped_not_exist": "Ignoré (n'existe pas) : {path}",
        "status_choose_receiver": "Choisissez un récepteur pour démarrer le transfert chiffré.",
        "status_selection_cleared": "Sélection effacée.",
        "status_refreshing_interfaces": "Actualisation des interfaces réseau...",
        "status_interfaces_updated": "Interfaces réseau mises à jour. Vous devrez peut-être redémarrer le scan/la réception.",
        "status_transfer_cancelled": "Transfert annulé.",
        "status_transfer_cancelled_by_user": "Transfert annulé par l'utilisateur.",
        "status_announcing_as_receiver": "Annonce de l'appareil sur {ip}:{port} en tant que Récepteur...",
        "status_stopping_announcement": "Arrêt de l'annonce...",
        "status_trusted_receiver": "Récepteur de confiance détecté ; la vérification manuelle est ignorée.",
        "status_file_selection_cancelled": "Sélection de fichier annulée.",
        "status_folder_selection_cancelled": "Sélection de dossier annulée.",
        "status_transfer_in_progress": "Transfert déjà en cours, veuillez patienter.",
        "status_select_files_first": "Sélectionnez d'abord un ou plusieurs fichiers ou dossiers.",
        "status_invalid_port": "Port invalide : {port}. Doit être compris entre 1 et 65535.",
        "status_invalid_subnet_format": "Format de sous-réseau invalide : {subnet}",
        "status_preparing_transfer": "Préparation du transfert chiffré...",
        "status_found_receiver_details": "Récepteur trouvé : {name} à {ip}:{port}",
        "status_requesting_firewall_perms": "Demande d'autorisations de pare-feu... Veuillez accepter l'invite UAC.",
        "status_firewall_not_configured": "Pare-feu non configuré. La découverte et la réception peuvent échouer.",
        "status_receiver_disconnected": "Récepteur déconnecté : {name}",
        "status_enter_valid_sender_ip": "Entrez une adresse IP valide pour l'interface de l'expéditeur.",
        "status_scanning_on_target": "Recherche de récepteurs sur {target}...",
        "status_enter_subnet": "Veuillez entrer un sous-réseau à scanner.",
        "status_subnet_scan_complete": "Scan de sous-réseau terminé.",
        "status_scanning_subnet": "Scan du sous-réseau {subnet} sur le port {port}...",
        "status_enter_valid_listen_ip": "Entrez une adresse IP valide pour l'écoute.",
        "status_receiver_start_failed": "Échec du démarrage du serveur récepteur.",
        "status_ready_to_receive_on": "Prêt à recevoir sur {ip}:{port}.",
        "status_receiving_stopped": "Réception arrêtée.",
        "status_listening_securely_on": "Écoute sécurisée sur {addrs}",
        "status_incoming_connection": "Connexion entrante de {ip}",
        "status_blocked_public_ip": "Connexion depuis l'IP publique {ip} bloquée par la politique de pare-feu 'LAN uniquement'.",
        "status_blocked_invalid_ip": "Impossible de valider l'IP {ip}. Connexion bloquée.",
        "status_establishing_secure_connection": "Établissement de la connexion sécurisée…",
        "status_secure_channel_established": "Canal sécurisé établi.",
        "status_blocked_high_security": "Connexion de {ip} ({fp}) bloquée par la politique 'Haute sécurité' (non approuvé ou non sur la liste blanche).",
        "status_transfer_rejected": "Transfert rejeté.",
        "status_receiving_file": "Réception de {filename}…",
        "status_verifying_unpacking": "Transfert reçu. Vérification et décompression...",
        "status_client_disconnected_normal": "Le client s'est déconnecté après le transfert, ce qui est normal.",
        "status_received_successfully": "{filename} reçu avec succès.",
        "status_restarting_receiver": "Redémarrage du récepteur...",
        "status_settings_saved_restart": "Paramètres enregistrés. Redémarrez le récepteur pour appliquer.",
        "settings_saved_snackbar": "Paramètres enregistrés !",
        "status_transfer_failed": "Échec du transfert : {error}",
        "all_interfaces_target": "toutes les interfaces",

        # Erreurs
        "error_ip_required": "L'IP est requise",
        "error_invalid_port": "Port invalide",
        "error_subnet_required": "Le sous-réseau est requis",
        "error_invalid_ip": "Adresse IP invalide",
        "error_invalid_port_range": "Port invalide (1024-65535)",
        "error_bind_failed": "Échec de l'écoute sur {ip}:{port}. L'adresse est peut-être indisponible ou déjà utilisée.",

        # Gestionnaire de progression
        "role_sending": "Envoi",
        "role_receiving": "Réception",
        "progress_label": "{role} : {completed} sur {total} ({percent:.0f}%) - {speed}",
        "progress_label_no_speed": "{role} : {completed} sur {total} ({percent:.0f}%)",
    }


    # Add more languages here...

def set_language(lang: str):
    """Sets the active language for the session."""
    global _current_language
    if lang in _locales:
        _current_language = lang
    else:
        _current_language = DEFAULT_LANGUAGE

def get_string(key: str) -> str:
    """Gets a localized string for a given key."""
    return _locales.get(_current_language, _locales[DEFAULT_LANGUAGE]).get(key, f"<{key}>")

def get_available_languages() -> list[tuple[str, str]]:
    """Returns a list of available languages (code, name)."""
    # The order is preserved from Python 3.7+ based on insertion order in load_locales.
    return [(code, _language_names.get(code, code)) for code in _locales]

# Load locales on module import
load_locales()
